// Public API for @noiselang/core — the Noise engine compiled to WebAssembly.
//
// The .wasm binary ships inside this package (see ./wasm, generated by `wasm-pack build`). The
// generated glue instantiates it via `new URL('noise_bg.wasm', import.meta.url)`, so any bundler
// that understands that pattern (Vite, Rollup, webpack 5, esbuild) fingerprints the .wasm and
// emits it as an asset of the *consuming* app's build — no copying, no CDN, no runtime config.
import init, {
  run as wasmRun,
  run_with_introspection as wasmRunIntrospect,
  version as wasmVersion,
} from '../wasm/noise.js';

let ready: Promise<void> | null = null;

/**
 * Initialize the WASM module exactly once; subsequent calls await the same promise.
 *
 * Called implicitly by `run` / `runWithIntrospection` / `version`, so most callers never need it.
 * Call it directly to warm the engine (e.g. on app mount) so the first real run doesn't pay the
 * ~one-off instantiation cost.
 */
export function load(): Promise<void> {
  if (!ready) {
    // No argument → the glue resolves the .wasm via `new URL('noise_bg.wasm', import.meta.url)`,
    // i.e. the asset the consumer's bundler emitted next to this module.
    ready = init().then(() => undefined);
  }
  return ready;
}

/** Run-time counters from the engine — what the program actually computed (see Rust `stats`). */
export interface NoiseStats {
  /** Forcing operations (`P`/`E`/`Var`/`Q`/`sample`) the program ran. */
  forcings: number;
  /** Total Monte-Carlo draws across all forcings. */
  samples: number;
  /** Total per-lane operations executed (Σ draws × cone-node-count). */
  ops: number;
  /** Total random source draws (Σ draws × source-node-count). */
  rng_draws: number;
}

export interface NoiseResult {
  ok: boolean;
  /** Display form of the program's final value, or null for `unit` / on error. */
  value: string | null;
  /** Everything `Print` emitted, in order. */
  output: string;
  /** Error message (with a source span) on failure, else null. */
  error: string | null;
  /** Engine run-time counters (zeroed if a program forced no sampling). */
  stats: NoiseStats;
  /** Wall-clock time of the WASM `run` call, in milliseconds (measured here, not in Rust). */
  elapsedMs: number;
}

const ZERO_STATS: NoiseStats = { forcings: 0, samples: 0, ops: 0, rng_draws: 0 };

/** Parse + evaluate a Noise program. Never throws — failures come back in `error`. */
export async function run(src: string): Promise<NoiseResult> {
  await load();
  // Time only the engine call (module load is excluded — it's a one-off, not per-run cost).
  const t0 = performance.now();
  const raw = wasmRun(src);
  const elapsedMs = performance.now() - t0;
  const parsed = JSON.parse(raw) as Omit<NoiseResult, 'elapsedMs'>;
  // The defensive serialization-error fallback omits `stats`; default it so callers needn't guard.
  return { ...parsed, stats: parsed.stats ?? ZERO_STATS, elapsedMs };
}

/** The engine (crate) version, e.g. `"0.1.1"`. */
export async function version(): Promise<string> {
  await load();
  return wasmVersion();
}

// --- variable introspection (the "inspect without editing the code" path) --------------------

/** A live top-level binding of the program — what a variable picker would list. */
export interface Binding {
  name: string;
  /** Value kind, e.g. `dist<number>` / `dist<bool>` (introspectable) or `number` / `array`. */
  kind: string;
}

/** A histogram to draw: equal-width buckets `bins` spanning `[lo, hi]`. */
export interface Hist {
  lo: number;
  hi: number;
  bins: number[];
}

/** One introspection result, tagged by `type` (mirrors the Rust `IntrospectionOut`). */
export type Introspection =
  | {
      type: 'dist1';
      label: string;
      n: number;
      mean: number;
      sd: number;
      min: number;
      max: number;
      q05: number;
      q25: number;
      q50: number;
      q75: number;
      q95: number;
      boolean: boolean;
      hist: Hist;
      head: number[];
    }
  | {
      type: 'dist2';
      label: string;
      label_b: string;
      n: number;
      corr: number;
      cov: number;
      mean_a: number;
      mean_b: number;
      sd_a: number;
      sd_b: number;
      points: [number, number][];
    }
  | {
      type: 'explain';
      label: string;
      sd: number;
      drivers: { name: string; corr: number; share: number }[];
    }
  | { type: 'value'; label: string; val: number; se: number }
  | {
      type: 'grid';
      label: string;
      rows: number;
      cols: number;
      /** true → vector (series view); false → matrix (heatmap view). */
      series: boolean;
      mean: number[];
      sd: number[];
    }
  | { type: 'corrmatrix'; label: string; n: number; corr: number[] }
  | { type: 'error'; error: string };

/** A request: one variable (`describe`/`explain`) or two (`corr`), with an optional condition. */
export interface IntrospectRequest {
  /** One or two variable *expressions*, evaluated in the program's scope. */
  vars: string[];
  /** Optional condition expression — `describe(v | given)`. */
  given?: string;
  /** When true, the one-variable request becomes `explain(v)` (driver fan-out). */
  explain?: boolean;
  /** When true, a single (array) variable becomes `corr(v)` (element correlation heatmap). */
  correlate?: boolean;
}

/** One item in the program's output stream: a `Print` line or a `plot::*` chart, in source order. */
export type LogItem = { kind: 'text'; text: string } | { kind: 'plot'; plot: Introspection };

export interface NoiseIntrospectResult extends NoiseResult {
  /** The program's live top-level variables (for a picker). */
  bindings: Binding[];
  /** One result per request, in request order. */
  introspections: Introspection[];
  /** The output stream in source order: `Print` lines and `plot::*` charts, interleaved. */
  log: LogItem[];
}

/**
 * Run a program and, against its retained scope, resolve a list of introspection requests — the
 * sidecar that powers a variable inspector. Passing `[]` requests still returns `bindings`, so a
 * plain run can populate a variable picker. Never throws; failures surface in `error` (and
 * per-request failures as `{ type: 'error' }` entries).
 */
export async function runWithIntrospection(
  src: string,
  requests: IntrospectRequest[],
): Promise<NoiseIntrospectResult> {
  await load();
  const t0 = performance.now();
  const raw = wasmRunIntrospect(src, JSON.stringify(requests));
  const elapsedMs = performance.now() - t0;
  const parsed = JSON.parse(raw) as Omit<NoiseIntrospectResult, 'elapsedMs'>;
  return {
    ...parsed,
    stats: parsed.stats ?? ZERO_STATS,
    bindings: parsed.bindings ?? [],
    introspections: parsed.introspections ?? [],
    log: parsed.log ?? [],
    elapsedMs,
  };
}
