// Public API for @noiselang/core — the Noise engine compiled to WebAssembly.
//
// The .wasm binary ships inside this package (see ./wasm, generated by `wasm-pack build`). The
// generated glue instantiates it via `new URL('noise_bg.wasm', import.meta.url)`, so any bundler
// that understands that pattern (Vite, Rollup, webpack 5, esbuild) fingerprints the .wasm and
// emits it as an asset of the *consuming* app's build — no copying, no CDN, no runtime config.
import init, {
  run as wasmRun,
  run_with_introspection as wasmRunIntrospect,
  meta as wasmMeta,
  version as wasmVersion,
} from '../wasm/noise.js';

let ready: Promise<void> | null = null;

/**
 * Initialize the WASM module exactly once; subsequent calls await the same promise.
 *
 * Called implicitly by `run` / `runWithIntrospection` / `version`, so most callers never need it.
 * Call it directly to warm the engine (e.g. on app mount) so the first real run doesn't pay the
 * ~one-off instantiation cost.
 */
export function load(): Promise<void> {
  if (!ready) {
    // No argument → the glue resolves the .wasm via `new URL('noise_bg.wasm', import.meta.url)`,
    // i.e. the asset the consumer's bundler emitted next to this module.
    ready = init().then(() => undefined);
  }
  return ready;
}

/** Run-time counters from the engine — what the program actually computed (see Rust `stats`). */
export interface NoiseStats {
  /** Forcing operations (`P`/`E`/`Var`/`Q`/`sample`) the program ran. */
  forcings: number;
  /** Total Monte-Carlo draws across all forcings. */
  samples: number;
  /** Total per-lane operations executed (Σ draws × cone-node-count). */
  ops: number;
  /** Total random source draws (Σ draws × source-node-count). */
  rng_draws: number;
}

const ZERO_STATS: NoiseStats = { forcings: 0, samples: 0, ops: 0, rng_draws: 0 };

// --- the Document contract (PLAN-LITERATE §D5) -----------------------------------------------
//
// A run returns exactly one `Document`: meta (frontmatter) + a flat, ordered array of typed
// blocks (code, notes, plots, inputs) + the comment layer + the result (which also carries the
// input manifest). Every view (Preview, plots-only, output-only) is a pure filter over `blocks`.

/** A half-open byte range `[start, end)` into the source. */
export interface Span {
  start: number;
  end: number;
}

/** One block in the flat array. `code` is verbatim source; `note`/`plot`/`input` are emissions
 * carrying the `stmt_span` of the statement that produced them. */
export type Block = CodeBlock | NoteBlock | PlotBlock | InputBlock;

/** A verbatim source segment — one statement group. */
export interface CodeBlock {
  kind: 'code';
  source: string;
  span: Span;
}

/** An emitted note — a rendered template or a `Print` call. `syntax` is the fence tag (`md`, …). */
export interface NoteBlock {
  kind: 'note';
  text: string;
  syntax: string | null;
  stmt_span: Span;
}

/** An emitted `plot::*` chart. Same shape as an introspection `Plot`, plus its producing statement. */
export interface PlotBlock {
  kind: 'plot';
  title: string;
  text: string;
  charts: ChartSpec[];
  stmt_span: Span;
}

/** An inline **input control** (`input::…`, PLAN-INPUTS): a host-tunable parameter, rendered as a
 *  slider/checkbox right after the code group that declares it. Carries its resolved current `value`. */
export interface InputBlock extends InputSpec {
  kind: 'input';
}

/** One comment in the annotation layer. `code_span` is the code it annotates (null = detached prose). */
export interface Comment {
  text: string;
  self_span: Span;
  code_span: Span | null;
}

/** The program's final value, as `{ kind, text }` — `text` is the display form, `kind` for styling. */
export interface DocValue {
  kind: string;
  text: string;
}

/** A spanned error (lex/parse/runtime). The blocks up to the failure are still present. */
export interface DocError {
  message: string;
  span: Span;
}

/** Set when the run hit the emission cap. */
export interface Truncated {
  dropped: number;
  first_dropped_stmt_span: Span;
}

export interface DocResult {
  value: DocValue | null;
  error: DocError | null;
  stats: NoiseStats;
  truncated: Truncated | null;
  /** The run's **input manifest** (PLAN-INPUTS §3): every `input::` declared, resolved, in
   *  declaration order. A host reads this to render controls and prune stale overrides. */
  inputs: InputSpec[];
}

/** Frontmatter meta carried by a document (same shape as `meta()` minus `ok`). Purely descriptive —
 *  tunable parameters are inline `input::…` calls, discovered from the run (`result.inputs`). */
export interface DocMeta {
  title?: string;
  /** A paper-style abstract — prose a literate host renders under the title. */
  abstract?: string;
  /** Free-form keyword tags (a paper's "Keywords:" line). */
  tags: string[];
  extra: Record<string, unknown>;
}

/** The wire `Document` — exactly what the engine returns. */
export interface NoiseDocument {
  meta: DocMeta;
  blocks: Block[];
  comments: Comment[];
  result: DocResult;
}

/**
 * A run: the `Document` plus client-side conveniences (`ok`/`value`/`output`/`error`/`stats`/`log`
 * derived from `blocks`+`result`, and the measured `elapsedMs`). The wire format is the pure
 * `Document`; these fields are added here so simple callers (demos) don't reach into `result`.
 */
export interface NoiseResult extends NoiseDocument {
  /** `true` when the run finished without error. */
  ok: boolean;
  /** Display form of the final value, or null for `unit` / on error. */
  value: string | null;
  /** Every note's text, joined by newlines (the old `Print` log). */
  output: string;
  /** Error message (with a source span) on failure, else null. */
  error: string | null;
  /** Engine run-time counters. */
  stats: NoiseStats;
  /** Notes + plots in emission order, in the legacy `LogItem` shape (a filter over `blocks`). */
  log: LogItem[];
  /** Wall-clock time of the run, in milliseconds (measured here, not in Rust). */
  elapsedMs: number;
}

/** Derive the client-side convenience fields from a wire `Document`. */
function enrich(doc: NoiseDocument, elapsedMs: number): NoiseResult {
  const log: LogItem[] = [];
  const outputLines: string[] = [];
  for (const b of doc.blocks) {
    if (b.kind === 'note') {
      log.push({ kind: 'text', text: b.text });
      outputLines.push(b.text);
    } else if (b.kind === 'plot') {
      log.push({ kind: 'plot', title: b.title, text: b.text, charts: b.charts });
    }
  }
  return {
    ...doc,
    ok: doc.result.error === null,
    value: doc.result.value?.text ?? null,
    output: outputLines.join('\n'),
    error: doc.result.error?.message ?? null,
    stats: doc.result.stats ?? ZERO_STATS,
    log,
    elapsedMs,
  };
}

/** A concrete input value a host passes as an override — a number (real/int) or a bool. */
export type InputValue = number | boolean;

/** An input's declared type. `real` is the continuous slider; `int` snaps to whole numbers. */
export type InputKind = 'real' | 'int' | 'bool';

/** A resolved input (PLAN-INPUTS): the spec declared by an `input::…` call plus its current `value`
 *  and the `stmt_span` of the declaring statement. This is both an `input` block and a
 *  `result.inputs[]` manifest entry. */
export interface InputSpec {
  name: string;
  type: InputKind;
  min?: number;
  max?: number;
  step?: number;
  default: InputValue;
  /** The resolved current value (host override, else default — clamped/snapped). */
  value: InputValue;
  /** Optional human label for the UI (falls back to `name`). */
  label?: string;
  stmt_span: Span;
}

/** Input overrides keyed by input name. Values are clamped/snapped by the engine. */
export type InputOverrides = Record<string, InputValue>;

/** Run options: input overrides for now, sample budget/seed later. */
export interface RunOpts {
  /** Override inline `input::…` parameters by name. */
  inputs?: InputOverrides;
}

/** Serialize `RunOpts` to the JSON the WASM boundary expects (or `undefined` when empty). */
function optsToJson(opts?: RunOpts): string | undefined {
  if (!opts?.inputs || Object.keys(opts.inputs).length === 0) return undefined;
  return JSON.stringify({ inputs: opts.inputs });
}

/** Parse + evaluate a Noise program. `opts.inputs` tunes inline `input::…` parameters. Never throws
 * — failures come back in `error`. */
export async function run(src: string, opts?: RunOpts): Promise<NoiseResult> {
  await load();
  // Time only the engine call (module load is excluded — it's a one-off, not per-run cost).
  const t0 = performance.now();
  const raw = wasmRun(src, optsToJson(opts));
  const elapsedMs = performance.now() - t0;
  const doc = JSON.parse(raw) as NoiseDocument;
  return enrich(doc, elapsedMs);
}

// --- frontmatter (the "read metadata without running" path) ----------------------------------

/** A file's parsed frontmatter — what `meta` returns. Purely descriptive; tunable parameters are
 *  inline `input::…` calls, discovered from a run (`result.inputs`), not from here. */
export interface NoiseMeta {
  ok: boolean;
  /** The document title, if declared. */
  title?: string;
  /** A paper-style abstract — prose a literate host renders under the title. */
  abstract?: string;
  /** Free-form keyword tags (a paper's "Keywords:" line). */
  tags: string[];
  /** Unknown frontmatter keys, preserved verbatim (blurb, category, …). */
  extra: Record<string, unknown>;
  /** Set when the fence is malformed. */
  error?: string;
}

/**
 * Read a file's frontmatter **without running it** — the pure call a host uses for the pre-run paper
 * header. A file with no frontmatter returns `{ ok: true, tags: [], extra: {} }`; a malformed fence
 * returns `{ ok: false, error }`.
 */
export async function meta(src: string): Promise<NoiseMeta> {
  await load();
  const parsed = JSON.parse(wasmMeta(src)) as Partial<NoiseMeta>;
  return {
    ok: parsed.ok ?? false,
    title: parsed.title,
    abstract: parsed.abstract,
    tags: parsed.tags ?? [],
    extra: parsed.extra ?? {},
    error: parsed.error,
  };
}

/** The engine (crate) version, e.g. `"0.1.1"`. */
export async function version(): Promise<string> {
  await load();
  return wasmVersion();
}

// --- variable introspection (the "inspect without editing the code" path) --------------------

/** A live top-level binding of the program — what a variable picker would list. */
export interface Binding {
  name: string;
  /** Value kind, e.g. `dist<number>` / `dist<bool>` (introspectable) or `number` / `array`. */
  kind: string;
}

/**
 * A [Flint](https://github.com/microsoft/flint-chart) `ChartAssemblyInput` — a *semantic* chart
 * description (`{ data, semantic_types, chart_spec }`) that `flint-chart`'s `assembleVegaLite` /
 * `assembleECharts` / `assembleChartjs` compiles into a renderable backend spec. Opaque here: the
 * engine produces it, a renderer consumes it, and nothing in between needs to look inside.
 */
export type ChartSpec = Record<string, unknown>;

/**
 * One plot — what `plot::*` emits and what an introspection request resolves to.
 *
 * There is a single plot shape, not a union per chart kind: the engine already decided which chart
 * a histogram, a fan, or a correlation matrix is. Render `charts` by compiling each spec with a
 * stock Flint backend; when there is more than one, **layer them** (that is the fan — two quantile
 * bands with a median line on top, sharing an x scale by construction).
 *
 * `charts` may be empty (an exact scalar has nothing to draw). `text` always holds every number the
 * charts encode, so a text-only host loses the picture and nothing else.
 */
export interface Plot {
  /** The card heading, e.g. `hist(st)` or `fan(path)`. */
  title: string;
  /** One-line summary — the fallback when there is no renderer, and what the CLI prints. */
  text: string;
  /** Flint chart specs, back-to-front. Compile each; layer them if there is more than one. */
  charts: ChartSpec[];
  /** Set (with empty `charts`) when an introspection *request* failed — one bad request, one bad card. */
  error?: string;
}

/** A request: one variable (`describe`/`explain`) or two (`corr`), with an optional condition. */
export interface IntrospectRequest {
  /** One or two variable *expressions*, evaluated in the program's scope. */
  vars: string[];
  /** Optional condition expression — `describe(v | given)`. */
  given?: string;
  /** When true, the one-variable request becomes `explain(v)` (driver fan-out). */
  explain?: boolean;
  /** When true, a single (array) variable becomes `corr(v)` (element correlation heatmap). */
  correlate?: boolean;
}

/** One item in the program's output stream: a `Print` line or a `plot::*` chart, in source order. */
export type LogItem = ({ kind: 'text' } & { text: string }) | ({ kind: 'plot' } & Plot);

export interface NoiseIntrospectResult extends NoiseResult {
  /** The program's live top-level variables (for a picker). */
  bindings: Binding[];
  /** One result per request, in request order. */
  introspections: Plot[];
}

/**
 * Run a program → one `Document`, and against its retained scope resolve a list of introspection
 * requests — the sidecar that powers a variable inspector. Passing `[]` requests still returns
 * `bindings`, so a plain run can populate a variable picker. Never throws; failures surface in
 * `result.error` (and per-request failures as `{ error }` entries in `introspections`).
 */
export async function runWithIntrospection(
  src: string,
  requests: IntrospectRequest[],
  opts?: RunOpts,
): Promise<NoiseIntrospectResult> {
  await load();
  const t0 = performance.now();
  const raw = wasmRunIntrospect(src, JSON.stringify(requests), optsToJson(opts));
  const elapsedMs = performance.now() - t0;
  const parsed = JSON.parse(raw) as {
    document: NoiseDocument;
    bindings?: Binding[];
    introspections?: Plot[];
  };
  return {
    ...enrich(parsed.document, elapsedMs),
    bindings: parsed.bindings ?? [],
    introspections: parsed.introspections ?? [],
  };
}
