// Public API for @noiselang/core — the Noise engine compiled to WebAssembly.
//
// The .wasm binary ships inside this package (see ./wasm, generated by `wasm-pack build`). The
// generated glue instantiates it via `new URL('noise_bg.wasm', import.meta.url)`, so any bundler
// that understands that pattern (Vite, Rollup, webpack 5, esbuild) fingerprints the .wasm and
// emits it as an asset of the *consuming* app's build — no copying, no CDN, no runtime config.
import init, {
  run as wasmRun,
  run_with_introspection as wasmRunIntrospect,
  meta as wasmMeta,
  version as wasmVersion,
} from '../wasm/noise.js';

let ready: Promise<void> | null = null;

/**
 * Initialize the WASM module exactly once; subsequent calls await the same promise.
 *
 * Called implicitly by `run` / `runWithIntrospection` / `version`, so most callers never need it.
 * Call it directly to warm the engine (e.g. on app mount) so the first real run doesn't pay the
 * ~one-off instantiation cost.
 */
export function load(): Promise<void> {
  if (!ready) {
    // No argument → the glue resolves the .wasm via `new URL('noise_bg.wasm', import.meta.url)`,
    // i.e. the asset the consumer's bundler emitted next to this module.
    ready = init().then(() => undefined);
  }
  return ready;
}

/** Run-time counters from the engine — what the program actually computed (see Rust `stats`). */
export interface NoiseStats {
  /** Forcing operations (`P`/`E`/`Var`/`Q`/`sample`) the program ran. */
  forcings: number;
  /** Total Monte-Carlo draws across all forcings. */
  samples: number;
  /** Total per-lane operations executed (Σ draws × cone-node-count). */
  ops: number;
  /** Total random source draws (Σ draws × source-node-count). */
  rng_draws: number;
}

export interface NoiseResult {
  ok: boolean;
  /** Display form of the program's final value, or null for `unit` / on error. */
  value: string | null;
  /** Everything `Print` emitted, in order. */
  output: string;
  /** Error message (with a source span) on failure, else null. */
  error: string | null;
  /** Engine run-time counters (zeroed if a program forced no sampling). */
  stats: NoiseStats;
  /** Wall-clock time of the WASM `run` call, in milliseconds (measured here, not in Rust). */
  elapsedMs: number;
}

const ZERO_STATS: NoiseStats = { forcings: 0, samples: 0, ops: 0, rng_draws: 0 };

/** A concrete knob value a host passes as an override — a number (int/float) or a bool. */
export type KnobValue = number | boolean;

/** Knob overrides keyed by knob name. Values are clamped/snapped by the engine. */
export type KnobOverrides = Record<string, KnobValue>;

/** Run options: knob overrides for now, sample budget/seed later. */
export interface RunOpts {
  knobs?: KnobOverrides;
}

/** Serialize `RunOpts` to the JSON the WASM boundary expects (or `undefined` when empty). */
function optsToJson(opts?: RunOpts): string | undefined {
  if (!opts?.knobs || Object.keys(opts.knobs).length === 0) return undefined;
  return JSON.stringify({ knobs: opts.knobs });
}

/** Parse + evaluate a Noise program. `opts.knobs` tunes frontmatter knobs. Never throws — failures
 * come back in `error`. */
export async function run(src: string, opts?: RunOpts): Promise<NoiseResult> {
  await load();
  // Time only the engine call (module load is excluded — it's a one-off, not per-run cost).
  const t0 = performance.now();
  const raw = wasmRun(src, optsToJson(opts));
  const elapsedMs = performance.now() - t0;
  const parsed = JSON.parse(raw) as Omit<NoiseResult, 'elapsedMs'>;
  // The defensive serialization-error fallback omits `stats`; default it so callers needn't guard.
  return { ...parsed, stats: parsed.stats ?? ZERO_STATS, elapsedMs };
}

// --- frontmatter + knobs (the "read metadata without running" path) --------------------------

/** A knob's declared type. `choice` is reserved for a later phase. */
export type KnobKind = 'int' | 'float' | 'bool' | 'choice';

/** A typed, host-tunable global declared in a file's frontmatter (PLAN-LITERATE §D2). */
export interface Knob {
  name: string;
  type: KnobKind;
  min?: number;
  max?: number;
  step?: number;
  default: KnobValue;
  /** Optional human label for the UI (falls back to `name`). */
  label?: string;
}

/** A file's parsed frontmatter — what `meta` returns. */
export interface NoiseMeta {
  ok: boolean;
  /** The document title, if declared. */
  title?: string;
  /** Declared knobs, in source order (render sliders top-to-bottom). */
  knobs: Knob[];
  /** Unknown frontmatter keys, preserved verbatim (blurb, category, …). */
  extra: Record<string, unknown>;
  /** Set when the fence is malformed. */
  error?: string;
}

/**
 * Read a file's frontmatter **without running it** — the pure call a host uses to build a knob UI.
 * A file with no frontmatter returns `{ ok: true, knobs: [], extra: {} }`; a malformed fence returns
 * `{ ok: false, error }`.
 */
export async function meta(src: string): Promise<NoiseMeta> {
  await load();
  const parsed = JSON.parse(wasmMeta(src)) as Partial<NoiseMeta>;
  return {
    ok: parsed.ok ?? false,
    title: parsed.title,
    knobs: parsed.knobs ?? [],
    extra: parsed.extra ?? {},
    error: parsed.error,
  };
}

/** The engine (crate) version, e.g. `"0.1.1"`. */
export async function version(): Promise<string> {
  await load();
  return wasmVersion();
}

// --- variable introspection (the "inspect without editing the code" path) --------------------

/** A live top-level binding of the program — what a variable picker would list. */
export interface Binding {
  name: string;
  /** Value kind, e.g. `dist<number>` / `dist<bool>` (introspectable) or `number` / `array`. */
  kind: string;
}

/**
 * A [Flint](https://github.com/microsoft/flint-chart) `ChartAssemblyInput` — a *semantic* chart
 * description (`{ data, semantic_types, chart_spec }`) that `flint-chart`'s `assembleVegaLite` /
 * `assembleECharts` / `assembleChartjs` compiles into a renderable backend spec. Opaque here: the
 * engine produces it, a renderer consumes it, and nothing in between needs to look inside.
 */
export type ChartSpec = Record<string, unknown>;

/**
 * One plot — what `plot::*` emits and what an introspection request resolves to.
 *
 * There is a single plot shape, not a union per chart kind: the engine already decided which chart
 * a histogram, a fan, or a correlation matrix is. Render `charts` by compiling each spec with a
 * stock Flint backend; when there is more than one, **layer them** (that is the fan — two quantile
 * bands with a median line on top, sharing an x scale by construction).
 *
 * `charts` may be empty (an exact scalar has nothing to draw). `text` always holds every number the
 * charts encode, so a text-only host loses the picture and nothing else.
 */
export interface Plot {
  /** The card heading, e.g. `hist(st)` or `fan(path)`. */
  title: string;
  /** One-line summary — the fallback when there is no renderer, and what the CLI prints. */
  text: string;
  /** Flint chart specs, back-to-front. Compile each; layer them if there is more than one. */
  charts: ChartSpec[];
  /** Set (with empty `charts`) when an introspection *request* failed — one bad request, one bad card. */
  error?: string;
}

/** A request: one variable (`describe`/`explain`) or two (`corr`), with an optional condition. */
export interface IntrospectRequest {
  /** One or two variable *expressions*, evaluated in the program's scope. */
  vars: string[];
  /** Optional condition expression — `describe(v | given)`. */
  given?: string;
  /** When true, the one-variable request becomes `explain(v)` (driver fan-out). */
  explain?: boolean;
  /** When true, a single (array) variable becomes `corr(v)` (element correlation heatmap). */
  correlate?: boolean;
}

/** One item in the program's output stream: a `Print` line or a `plot::*` chart, in source order. */
export type LogItem = ({ kind: 'text' } & { text: string }) | ({ kind: 'plot' } & Plot);

export interface NoiseIntrospectResult extends NoiseResult {
  /** The program's live top-level variables (for a picker). */
  bindings: Binding[];
  /** One result per request, in request order. */
  introspections: Plot[];
  /** The output stream in source order: `Print` lines and `plot::*` charts, interleaved. */
  log: LogItem[];
}

/**
 * Run a program and, against its retained scope, resolve a list of introspection requests — the
 * sidecar that powers a variable inspector. Passing `[]` requests still returns `bindings`, so a
 * plain run can populate a variable picker. Never throws; failures surface in `error` (and
 * per-request failures as `{ type: 'error' }` entries).
 */
export async function runWithIntrospection(
  src: string,
  requests: IntrospectRequest[],
  opts?: RunOpts,
): Promise<NoiseIntrospectResult> {
  await load();
  const t0 = performance.now();
  const raw = wasmRunIntrospect(src, JSON.stringify(requests), optsToJson(opts));
  const elapsedMs = performance.now() - t0;
  const parsed = JSON.parse(raw) as Omit<NoiseIntrospectResult, 'elapsedMs'>;
  return {
    ...parsed,
    stats: parsed.stats ?? ZERO_STATS,
    bindings: parsed.bindings ?? [],
    introspections: parsed.introspections ?? [],
    log: parsed.log ?? [],
    elapsedMs,
  };
}
